#!/usr/bin/env python2
#-*-python-*-

import hashlib

class Link():
    def __init__(self, parent, data):
        self.parent = parent
        self.data = data
        self.addr = hashlib.md5(str(self.parent) + str(self.data)).hexdigest()

    def show(self):
        print('+---------------------------------------------------------------------+')
        print('| parent                           | addr                             |')
        if self.parent:
            p = self.parent
        else:
            p = 'None'
        print('| %-32s | %s |' % (p, self.addr))
        print('+---------------------------------------------------------------------+')
        print('|%-69s|' % (self.data))
        print('+---------------------------------------------------------------------+')
        
l1 = Link(None, 'Amy pays Joe $5')
l2 = Link(l1.addr, 'Joe pays Amy $7')
l3 = Link(l2.addr, 'Joe pays Lou $1')

print('unhacked')
for l in [l1, l2, l3]:
    l.show()

lhacker = Link(l1.addr, 'Amy -> Joe $1e6')
l2.parent = lhacker.addr
l3.parent = l2.addr

print('hacked')
for l in [l1, lhacker, l2, l3]:
    l.show()

