#!/usr/bin/env python2
#-*-python-*-

import random

class Link():
    def __init__(self, parent, data):
        self.addr = random.randint(0, 256)
        self.parent = parent
        self.data = data

    def show(self):
        print('+---------------+')
        print('| parent | addr |')
        if self.parent:
            p = hex(self.parent)
        else:
            p = 'None'
        print('| %s   | %s |' % (p, hex(self.addr)))
        print('+---------------+')
        print('|%-15s|' % (self.data))
        print('+---------------+')
        
l1 = Link(None, 'Amy pays Joe $5')
l2 = Link(l1.addr, 'Joe pays Amy $7')
l3 = Link(l2.addr, 'Joe pays Lou $1')

print('unhacked')
for l in [l1, l2, l3]:
    l.show()

lhacker = Link(l1.addr, 'Amy -> Joe $1e6')
l2.parent = lhacker.addr

print('hacked')
for l in [l1, lhacker, l2, l3]:
    l.show()

